# Generated by Django 4.2.8 on 2025-04-08 15:19

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='NguoiDung',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('ma_nguoi_dung', models.AutoField(primary_key=True, serialize=False)),
                ('ten_dang_nhap', models.CharField(max_length=150, unique=True)),
                ('vai_tro', models.CharField(choices=[('khach_hang', 'Khách Hàng'), ('nhan_vien', 'Nhân Viên'), ('quan_ly', 'Quản Lý')], default='khach_hang', max_length=20)),
                ('diem_tich_luy', models.IntegerField(default=0)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('so_dien_thoai', models.CharField(blank=True, max_length=15, null=True)),
                ('ho_ten', models.CharField(blank=True, max_length=100, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='Các nhóm mà người dùng này thuộc về.', related_name='nguoi_dung_groups', to='auth.group')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Các quyền cụ thể của người dùng này.', related_name='nguoi_dung_permissions', to='auth.permission')),
            ],
            options={
                'verbose_name': 'Người Dùng',
                'verbose_name_plural': 'Người Dùng',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='BanAn',
            fields=[
                ('ma_ban', models.AutoField(primary_key=True, serialize=False)),
                ('so_ban', models.CharField(max_length=10, unique=True)),
                ('suc_chua', models.PositiveIntegerField()),
                ('trang_thai', models.CharField(choices=[('trong', 'Trống'), ('co_nguoi', 'Có Người')], default='trong', max_length=20)),
            ],
            options={
                'verbose_name': 'Bàn Ăn',
                'verbose_name_plural': 'Bàn Ăn',
            },
        ),
        migrations.CreateModel(
            name='BaoCaoDoanhThu',
            fields=[
                ('ma_bao_cao', models.AutoField(primary_key=True, serialize=False)),
                ('ky_bao_cao', models.CharField(choices=[('hang_ngay', 'Hàng Ngày'), ('hang_tuan', 'Hàng Tuần'), ('hang_thang', 'Hàng Tháng')], max_length=20)),
                ('tong_doanh_thu', models.DecimalField(decimal_places=0, max_digits=15)),
                ('ngay_bat_dau', models.DateTimeField()),
                ('ngay_ket_thuc', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'Báo Cáo Doanh Thu',
                'verbose_name_plural': 'Báo Cáo Doanh Thu',
            },
        ),
        migrations.CreateModel(
            name='PhienTroChuyen',
            fields=[
                ('ma_phien', models.AutoField(primary_key=True, serialize=False)),
                ('ngay_tao', models.DateTimeField(auto_now_add=True)),
                ('nguoi_dung', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phien_tro_chuyen_nguoi_dung', to=settings.AUTH_USER_MODEL)),
                ('nhan_vien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phien_tro_chuyen_nhan_vien', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Phiên Trò Chuyện',
                'verbose_name_plural': 'Phiên Trò Chuyện',
            },
        ),
        migrations.CreateModel(
            name='ThucDon',
            fields=[
                ('ma_mon', models.AutoField(primary_key=True, serialize=False)),
                ('ten_mon', models.CharField(max_length=100)),
                ('gia_tien', models.DecimalField(decimal_places=0, max_digits=10)),
                ('hinh_anh', models.ImageField(blank=True, null=True, upload_to='hinh_anh_mon_an/')),
                ('ngay_tao', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Thực Đơn',
                'verbose_name_plural': 'Thực Đơn',
            },
        ),
        migrations.CreateModel(
            name='TinNhan',
            fields=[
                ('ma_tin_nhan', models.AutoField(primary_key=True, serialize=False)),
                ('noi_dung', models.TextField()),
                ('thoi_gian_gui', models.DateTimeField(auto_now_add=True)),
                ('nguoi_gui', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('phien_tro_chuyen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tin_nhan', to='myapp.phientrochuyen')),
            ],
            options={
                'verbose_name': 'Tin Nhắn',
                'verbose_name_plural': 'Tin Nhắn',
            },
        ),
        migrations.CreateModel(
            name='ThongBao',
            fields=[
                ('ma_thong_bao', models.AutoField(primary_key=True, serialize=False)),
                ('tieu_de', models.CharField(max_length=200)),
                ('noi_dung', models.TextField()),
                ('trang_thai', models.CharField(choices=[('cho_duyet', 'Chờ Duyệt'), ('da_duyet', 'Đã Duyệt')], default='cho_duyet', max_length=20)),
                ('ngay_tao', models.DateTimeField(auto_now_add=True)),
                ('nguoi_tao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thong_bao', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Thông Báo',
                'verbose_name_plural': 'Thông Báo',
            },
        ),
        migrations.CreateModel(
            name='MonYeuThich',
            fields=[
                ('ma_mon_yeu_thich', models.AutoField(primary_key=True, serialize=False)),
                ('mon_an', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.thucdon')),
                ('nguoi_dung', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mon_yeu_thich', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Món Yêu Thích',
                'verbose_name_plural': 'Món Yêu Thích',
            },
        ),
        migrations.CreateModel(
            name='MaGiamGia',
            fields=[
                ('ma_giam_gia', models.AutoField(primary_key=True, serialize=False)),
                ('ma_code', models.CharField(max_length=20, unique=True)),
                ('gia_tri', models.DecimalField(decimal_places=0, max_digits=10)),
                ('ngay_het_han', models.DateTimeField()),
                ('nguoi_dung', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ma_giam_gia', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Mã Giảm Giá',
                'verbose_name_plural': 'Mã Giảm Giá',
            },
        ),
        migrations.CreateModel(
            name='DonHang',
            fields=[
                ('ma_don_hang', models.AutoField(primary_key=True, serialize=False)),
                ('loai_don_hang', models.CharField(choices=[('truc_tuyen', 'Trực Tuyến'), ('tai_quan', 'Tại Quán'), ('mang_di', 'Mang Đi')], max_length=20)),
                ('trang_thai', models.CharField(choices=[('cho_xac_nhan', 'Chờ Xác Nhận'), ('dang_chuan_bi', 'Đang Chuẩn Bị'), ('hoan_tat', 'Hoàn Tất'), ('da_huy', 'Đã Hủy')], default='cho_xac_nhan', max_length=20)),
                ('dia_chi', models.TextField(blank=True, null=True)),
                ('ngay_tao', models.DateTimeField(auto_now_add=True)),
                ('tong_tien', models.DecimalField(decimal_places=0, default=0, max_digits=10)),
                ('nguoi_dung', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='don_hang', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Đơn Hàng',
                'verbose_name_plural': 'Đơn Hàng',
            },
        ),
        migrations.CreateModel(
            name='DatBan',
            fields=[
                ('ma_dat_ban', models.AutoField(primary_key=True, serialize=False)),
                ('thoi_gian_dat', models.DateTimeField()),
                ('so_nguoi', models.PositiveIntegerField()),
                ('trang_thai', models.CharField(choices=[('cho_xac_nhan', 'Chờ Xác Nhận'), ('da_xac_nhan', 'Đã Xác Nhận'), ('da_huy', 'Đã Hủy')], default='cho_xac_nhan', max_length=20)),
                ('ten_khach_hang', models.CharField(blank=True, max_length=100, null=True)),
                ('so_dien_thoai_khach_hang', models.CharField(blank=True, max_length=15, null=True)),
                ('ban_an', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.banan')),
                ('nguoi_dung', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dat_ban', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Đặt Bàn',
                'verbose_name_plural': 'Đặt Bàn',
            },
        ),
        migrations.CreateModel(
            name='DanhGia',
            fields=[
                ('ma_danh_gia', models.AutoField(primary_key=True, serialize=False)),
                ('diem_danh_gia', models.PositiveIntegerField()),
                ('binh_luan', models.TextField(blank=True, null=True)),
                ('ngay_tao', models.DateTimeField(auto_now_add=True)),
                ('don_hang', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='myapp.donhang')),
                ('nguoi_dung', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='danh_gia', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Đánh Giá',
                'verbose_name_plural': 'Đánh Giá',
            },
        ),
        migrations.CreateModel(
            name='ChiTietDonHang',
            fields=[
                ('ma_chi_tiet', models.AutoField(primary_key=True, serialize=False)),
                ('so_luong', models.PositiveIntegerField()),
                ('tuy_chinh', models.TextField(blank=True, null=True)),
                ('gia_tien', models.DecimalField(decimal_places=0, max_digits=10)),
                ('don_hang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chi_tiet_don_hang', to='myapp.donhang')),
                ('mon_an', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.thucdon')),
            ],
            options={
                'verbose_name': 'Chi Tiết Đơn Hàng',
                'verbose_name_plural': 'Chi Tiết Đơn Hàng',
            },
        ),
    ]
