# Generated by Django 4.2.8 on 2025-04-08 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nguoidung',
            name='ten_dang_nhap',
        ),
    ]
