# Generated by Django 4.2.8 on 2025-05-01 16:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_remove_nguoidung_ten_dang_nhap'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phientrochuyen',
            name='nguoi_dung',
        ),
        migrations.RemoveField(
            model_name='phientrochuyen',
            name='nhan_vien',
        ),
        migrations.AddField(
            model_name='phientrochuyen',
            name='cua_hang',
            field=models.ForeignKey(blank=True, limit_choices_to={'vai_tro__in': ['nhan_vien', 'quan_ly']}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='phien_tro_chuyen_quan', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='phientrochuyen',
            name='khach_hang',
            field=models.ForeignKey(default=1, limit_choices_to={'vai_tro': 'khach_hang'}, on_delete=django.db.models.deletion.CASCADE, related_name='phien_tro_chuyen_khach_hang', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='thucdon',
            name='trang_thai',
            field=models.BooleanField(default=True),
        ),
    ]
