# Generated by Django 4.2.8 on 2025-05-05 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_remove_thucdon_trang_thai_thucdon_da_an'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donhang',
            name='nguoi_dung',
        ),
        migrations.AddField(
            model_name='donhang',
            name='ten_khach_hang',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='donhang',
            name='trang_thai',
            field=models.CharField(choices=[('da_xac_nhan', 'Đã xác nhận'), ('dang_che_bien', 'Đang chế biến'), ('dang_giao', 'Đang giao'), ('hoan_thanh', 'Đã hoàn thành'), ('da_huy', 'Đã hủy')], default='cho_xac_nhan', max_length=20),
        ),
    ]
