# Generated by Django 4.2.8 on 2025-05-05 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_remove_donhang_nguoi_dung_donhang_ten_khach_hang_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='donhang',
            name='thanh_toan',
            field=models.CharField(choices=[('da_thanh_toan', 'Đã thanh toán'), ('chua_thanh_toan', 'Chưa thanh toán')], default='chua_thanh_toan', max_length=20),
        ),
    ]
