# Generated by Django 4.2.8 on 2025-05-06 07:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_donhang_thanh_toan'),
    ]

    operations = [
        migrations.AddField(
            model_name='donhang',
            name='nguoi_dung',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='don_hang', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='donhang',
            name='trang_thai',
            field=models.CharField(choices=[('da_xac_nhan', 'Đã xác nhận'), ('dang_che_bien', 'Đang chế biến'), ('dang_giao', 'Đang giao'), ('hoan_thanh', 'Đã hoàn thành'), ('da_huy', 'Đã hủy')], default='da_xac_nhan', max_length=20),
        ),
    ]
