# Generated by Django 4.2.8 on 2025-05-24 02:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_danhgia_da_an_danhgia_phan_hoi'),
    ]

    operations = [
        migrations.CreateModel(
            name='GioHang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('so_luong', models.PositiveIntegerField(default=1)),
                ('ngay_them', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Giỏ Hàng',
                'verbose_name_plural': 'Giỏ Hàng',
            },
        ),
        migrations.AddField(
            model_name='thucdon',
            name='danh_muc',
            field=models.CharField(choices=[('Cà Phê', 'Cà Phê'), ('Trà Sữa', 'Trà Sữa'), ('Nước Ép', 'Nước Ép'), ('Đồ Ăn', 'Đồ Ăn')], default='Cà Phê', max_length=50),
        ),
        migrations.DeleteModel(
            name='MonYeuThich',
        ),
        migrations.AddField(
            model_name='giohang',
            name='mon_an',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.thucdon'),
        ),
        migrations.AddField(
            model_name='giohang',
            name='nguoi_dung',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gio_hang', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='giohang',
            unique_together={('nguoi_dung', 'mon_an')},
        ),
    ]
