# Generated by Django 4.2.8 on 2025-05-24 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_giohang_thucdon_danh_muc_delete_monyeuthich_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tinnhan',
            name='hinh_anh',
            field=models.ImageField(blank=True, null=True, upload_to='tin_nhan_images/'),
        ),
        migrations.AlterField(
            model_name='tinnhan',
            name='noi_dung',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='ThongBao',
        ),
    ]
