# Generated by Django 4.2.8 on 2025-05-24 11:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_tinnhan_hinh_anh_alter_tinnhan_noi_dung_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donhang',
            name='ten_khach_hang',
        ),
        migrations.AddField(
            model_name='donhang',
            name='phi_ship',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='donhang',
            name='so_dien_thoai',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='donhang',
            name='thoi_gian_dat',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='donhang',
            name='nguoi_dung',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='don_hang', to=settings.AUTH_USER_MODEL),
        ),
    ]
