# Generated by Django 4.2.8 on 2025-05-24 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_remove_donhang_ten_khach_hang_donhang_phi_ship_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='danhgia',
            name='hinh_anh',
            field=models.ImageField(blank=True, null=True, upload_to='danh_gia/'),
        ),
    ]
